language: perl6
perl6:
  - latest
  - 2016.12
os:
  - linux
  - osx
install:
  - rakudobrew build-zef
  - zef --depsonly install .
  - zef build .
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then make test-coverage; else make test; fi
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then bash <(curl -s https://codecov.io/bash); fi
