language: perl6
os:
  - linux
  - osx
sudo: false
perl6:
  - latest
  - 2016.12
install:
  - rakudobrew build-zef
  - zef --depsonly install .
  - zef build .
script:
  - make coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
